import { getMeetingSourceMetadata, type SourceType } from "@/lib/meetingTrust";

type VoteResult = {
	yes: number;
	no: number;
	abstain: number;
	passed: boolean;
};

type ReporterExportMeeting = {
	title: string;
	meetingDate: number;
	sourceUrl?: string | null;
	sourceType?: SourceType | null;
	contentHash?: string | null;
	processingError?: string | null;
	municipality?: {
		name: string;
		state: string;
	} | null;
	summary: {
		executiveSummary: string;
		keyDecisions: ReadonlyArray<{
			title: string;
			description: string;
			voteResult?: VoteResult;
			topics: ReadonlyArray<string>;
		}>;
		discussionTopics: ReadonlyArray<{
			topic: string;
			summary: string;
			category: string;
		}>;
		upcomingItems: ReadonlyArray<{
			title: string;
			expectedDate?: string;
		}>;
		topics: ReadonlyArray<string>;
		sourceUrl?: string | null;
		sourceType?: SourceType | null;
		sourceContentHash?: string | null;
		error?: string | null;
	} | null;
};

const AI_CAVEAT =
	"This export is AI-generated by Civic Observatory and is not official minutes.";
const CSV_CAVEAT = "AI-generated by Civic Observatory; not official minutes.";

export function buildReporterMarkdown(meeting: ReporterExportMeeting): string {
	const summary = meeting.summary;
	const { sourceUrl, sourceType, contentHash } =
		getMeetingSourceMetadata(meeting);
	const lines = [
		`# ${meeting.title}`,
		"",
		`Municipality: ${municipalityLabel(meeting)}`,
		`Meeting date: ${formatLongDate(meeting.meetingDate)}`,
		`Caveat: ${AI_CAVEAT}`,
	];

	if (sourceUrl) lines.push(`Source: ${sourceUrl}`);
	if (sourceType) lines.push(`Source type: ${sourceType}`);
	if (contentHash) {
		lines.push(`Source content hash: ${contentHash}`);
	}

	lines.push("", "## Executive Summary", "", summary?.executiveSummary ?? "");

	if (summary?.topics.length) {
		lines.push("", `Topics: ${summary.topics.join(", ")}`);
	}

	if (summary?.keyDecisions.length) {
		lines.push("", "## Key Decisions");
		for (const decision of summary.keyDecisions) {
			lines.push(
				"",
				`### ${decision.title}`,
				decision.description,
				`Vote: ${formatVote(decision.voteResult)}`,
			);
			if (decision.topics.length) {
				lines.push(`Topics: ${decision.topics.join(", ")}`);
			}
		}
	}

	if (summary?.discussionTopics.length) {
		lines.push("", "## Discussion Topics");
		for (const topic of summary.discussionTopics) {
			lines.push(
				"",
				`### ${topic.topic}`,
				topic.summary,
				`Category: ${topic.category}`,
			);
		}
	}

	if (summary?.upcomingItems.length) {
		lines.push("", "## Upcoming Items");
		for (const item of summary.upcomingItems) {
			lines.push(
				`- ${item.title}${item.expectedDate ? ` (${item.expectedDate})` : ""}`,
			);
		}
	}

	return `${lines.join("\n").trim()}\n`;
}

export function buildReporterCsv(meeting: ReporterExportMeeting): string {
	const summary = meeting.summary;
	const sourceUrl = getMeetingSourceMetadata(meeting).sourceUrl ?? "";
	const meetingDate = formatIsoDate(meeting.meetingDate);
	const municipality = municipalityLabel(meeting);
	const rows: string[][] = [
		[
			"section",
			"title",
			"description",
			"vote",
			"topics",
			"source_url",
			"meeting_date",
			"municipality",
			"caveat",
		],
		[
			"executive_summary",
			meeting.title,
			summary?.executiveSummary ?? "",
			"",
			summary?.topics.join("; ") ?? "",
			sourceUrl,
			meetingDate,
			municipality,
			CSV_CAVEAT,
		],
	];

	for (const decision of summary?.keyDecisions ?? []) {
		rows.push([
			"key_decision",
			decision.title,
			decision.description,
			formatVote(decision.voteResult),
			decision.topics.join("; "),
			sourceUrl,
			meetingDate,
			municipality,
			CSV_CAVEAT,
		]);
	}

	for (const topic of summary?.discussionTopics ?? []) {
		rows.push([
			"discussion_topic",
			topic.topic,
			topic.summary,
			"",
			topic.category,
			sourceUrl,
			meetingDate,
			municipality,
			CSV_CAVEAT,
		]);
	}

	for (const item of summary?.upcomingItems ?? []) {
		rows.push([
			"upcoming_item",
			item.title,
			item.expectedDate ?? "",
			"",
			"",
			sourceUrl,
			meetingDate,
			municipality,
			CSV_CAVEAT,
		]);
	}

	return `${rows
		.map((row, index) =>
			index === 0 ? row.join(",") : row.map(csvCell).join(","),
		)
		.join("\n")}\n`;
}

export function buildReporterExportFilename(
	meeting: ReporterExportMeeting,
	extension: "md" | "csv",
): string {
	return `${slugify(
		[
			meeting.municipality?.name,
			meeting.title,
			formatIsoDate(meeting.meetingDate),
		]
			.filter(Boolean)
			.join(" "),
	)}.${extension}`;
}

function municipalityLabel(meeting: ReporterExportMeeting) {
	if (!meeting.municipality) return "Unknown municipality";
	return `${meeting.municipality.name}, ${meeting.municipality.state}`;
}

function formatVote(vote?: VoteResult) {
	if (!vote) return "Not recorded";
	return `${vote.passed ? "passed" : "failed"} ${vote.yes}-${vote.no}-${vote.abstain}`;
}

function formatLongDate(timestamp: number) {
	return new Date(timestamp).toLocaleDateString("en-US", {
		month: "long",
		day: "numeric",
		year: "numeric",
		timeZone: "UTC",
	});
}

function formatIsoDate(timestamp: number) {
	return new Date(timestamp).toISOString().slice(0, 10);
}

function csvCell(value: string) {
	const guarded = /^[=+\-@\t\r\n]/.test(value) ? `'${value}` : value;
	return `"${guarded.replaceAll('"', '""')}"`;
}

function slugify(value: string) {
	return value
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "");
}
