import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Meeting summaries generated by AI
  summaries: defineTable({
    meetingTitle: v.string(),
    meetingDate: v.string(),
    meetingType: v.string(), // "city_council", "school_board", "planning_commission", etc.
    sourceUrl: v.optional(v.string()),

    // AI-generated content
    summary: v.string(),
    keyDecisions: v.array(v.string()),
    actionItems: v.array(v.object({
      description: v.string(),
      assignee: v.optional(v.string()),
      deadline: v.optional(v.string()),
    })),
    publicComments: v.optional(v.array(v.object({
      topic: v.string(),
      sentiment: v.string(), // "support", "opposition", "neutral"
      count: v.number(),
    }))),
    votingRecord: v.optional(v.array(v.object({
      item: v.string(),
      result: v.string(),
      votes: v.optional(v.object({
        yes: v.number(),
        no: v.number(),
        abstain: v.number(),
      })),
    }))),

    // Meta
    shareId: v.string(),
    isPublic: v.boolean(),
    userId: v.optional(v.string()),
    visitorId: v.optional(v.string()),
    latencyMs: v.number(),
    createdAt: v.number(),
  })
    .index("by_shareId", ["shareId"])
    .index("by_userId", ["userId", "createdAt"])
    .index("by_public_createdAt", ["isPublic", "createdAt"])
    .index("by_meetingType", ["meetingType", "createdAt"]),

  // Daily usage tracking for rate limiting
  dailyUsage: defineTable({
    identifier: v.string(),
    date: v.string(),
    summaryCount: v.number(),
  }).index("by_identifier_date", ["identifier", "date"]),

  // Users (from WorkOS authentication)
  users: defineTable({
    workosUserId: v.string(),
    email: v.string(),
    tier: v.union(v.literal("free"), v.literal("pro")),
    role: v.optional(
      v.union(v.literal("user"), v.literal("pro"), v.literal("admin"))
    ),
    createdAt: v.number(),
  }).index("by_workosUserId", ["workosUserId"]),
});
