// @vitest-environment jsdom
import {
	cleanup,
	fireEvent,
	render,
	screen,
	waitFor,
} from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ReporterExportDialog, SummaryMetadataPanel } from "./$meetingId";

const originalClipboard = Object.getOwnPropertyDescriptor(
	navigator,
	"clipboard",
);
const originalCreateObjectUrl = Object.getOwnPropertyDescriptor(
	URL,
	"createObjectURL",
);
const originalRevokeObjectUrl = Object.getOwnPropertyDescriptor(
	URL,
	"revokeObjectURL",
);
const originalExecCommand = Object.getOwnPropertyDescriptor(
	document,
	"execCommand",
);

describe("meeting summary trust metadata", () => {
	afterEach(() => {
		cleanup();
		vi.useRealTimers();
		vi.restoreAllMocks();
		restoreProperty(navigator, "clipboard", originalClipboard);
		restoreProperty(URL, "createObjectURL", originalCreateObjectUrl);
		restoreProperty(URL, "revokeObjectURL", originalRevokeObjectUrl);
		restoreProperty(document, "execCommand", originalExecCommand);
	});

	it("renders AI provenance and source metadata on the meeting detail page", () => {
		render(<SummaryMetadataPanel meeting={meetingWithSummaryMetadata} />);

		expect(screen.getByText("AI summary details")).toBeDefined();
		expect(
			screen.getByText("Civic Observatory AI analysis, not official minutes."),
		).toBeDefined();
		expect(screen.getByText("AI review status")).toBeDefined();
		expect(screen.getAllByText("AI-generated, unreviewed")).toHaveLength(2);
		expect(screen.getByText("Model")).toBeDefined();
		expect(screen.getByText("gpt-4.1-mini")).toBeDefined();
		expect(screen.getByText("Prompt")).toBeDefined();
		expect(screen.getByText("civic-summary-v2")).toBeDefined();
		expect(screen.getByText("Processing time")).toBeDefined();
		expect(screen.getByText("4.2s")).toBeDefined();
		expect(screen.getByText("Summary created")).toBeDefined();
		expect(screen.getByText("June 15")).toBeDefined();
		expect(screen.getByText("Source type")).toBeDefined();
		expect(screen.getByText("Scraped public record")).toBeDefined();
		expect(screen.getByText("Last checked")).toBeDefined();
		expect(screen.getByText("June 16")).toBeDefined();
	});

	it("renders copy-ready reporter exports with source metadata and no private fields", () => {
		render(
			<ReporterExportDialog
				meeting={reporterExportMeeting}
				open
				onOpenChange={() => {}}
			/>,
		);

		expect(screen.getByText("Reporter export")).toBeDefined();

		let output = screen.getByLabelText(
			"Reporter export output",
		) as HTMLTextAreaElement;
		expect(output.value).toContain("# Town Council Regular Meeting");
		expect(output.value).toContain(
			"Caveat: This export is AI-generated by Civic Observatory and is not official minutes.",
		);
		expect(output.value).toContain("Source: https://example.test/agenda.pdf");
		expect(output.value).toContain("Source content hash: summary-content-hash");
		expect(output.value).not.toContain("private-user-id");
		expect(output.value).not.toContain("subscription-secret");

		fireEvent.click(screen.getByRole("button", { name: "CSV" }));

		output = screen.getByLabelText(
			"Reporter export output",
		) as HTMLTextAreaElement;
		expect(output.value).toContain(
			"section,title,description,vote,topics,source_url,meeting_date,municipality,caveat",
		);
		expect(output.value).toContain(
			'"executive_summary","Town Council Regular Meeting","Council reviewed budget and grant items."',
		);
		expect(output.value).toContain(
			'"AI-generated by Civic Observatory; not official minutes."',
		);
		expect(output.value).not.toContain("private-user-id");
		expect(output.value).not.toContain("subscription-secret");
	});

	it("copies the active reporter export through the Clipboard API", async () => {
		const writeText = vi.fn().mockResolvedValue(undefined);
		Object.defineProperty(navigator, "clipboard", {
			configurable: true,
			value: { writeText },
		});
		render(
			<ReporterExportDialog
				meeting={reporterExportMeeting}
				open
				onOpenChange={() => {}}
			/>,
		);

		fireEvent.click(screen.getByRole("button", { name: "Copy" }));

		await waitFor(() => {
			expect(writeText).toHaveBeenCalledWith(
				expect.stringContaining("# Town Council Regular Meeting"),
			);
		});
		expect(screen.getByRole("button", { name: "Copied" })).toBeDefined();
	});

	it("falls back to execCommand when the Clipboard API is unavailable", async () => {
		const execCommand = vi.fn().mockReturnValue(true);
		Object.defineProperty(document, "execCommand", {
			configurable: true,
			value: execCommand,
		});
		Object.defineProperty(navigator, "clipboard", {
			configurable: true,
			value: undefined,
		});
		render(
			<ReporterExportDialog
				meeting={reporterExportMeeting}
				open
				onOpenChange={() => {}}
			/>,
		);

		fireEvent.click(screen.getByRole("button", { name: "Copy" }));

		await waitFor(() => {
			expect(execCommand).toHaveBeenCalledWith("copy");
		});
		expect(screen.getByRole("button", { name: "Copied" })).toBeDefined();
		expect(document.querySelectorAll("textarea")).toHaveLength(1);
	});

	it("downloads the active reporter export and defers blob URL cleanup", () => {
		vi.useFakeTimers();
		const createObjectURL = vi.fn().mockReturnValue("blob:reporter-export");
		const revokeObjectURL = vi.fn();
		Object.defineProperty(URL, "createObjectURL", {
			configurable: true,
			value: createObjectURL,
		});
		Object.defineProperty(URL, "revokeObjectURL", {
			configurable: true,
			value: revokeObjectURL,
		});
		const click = vi
			.spyOn(HTMLAnchorElement.prototype, "click")
			.mockImplementation(() => {});
		render(
			<ReporterExportDialog
				meeting={reporterExportMeeting}
				open
				onOpenChange={() => {}}
			/>,
		);

		fireEvent.click(screen.getByRole("button", { name: "Download" }));

		expect(createObjectURL).toHaveBeenCalledWith(expect.any(Blob));
		expect(click).toHaveBeenCalledOnce();
		expect(revokeObjectURL).not.toHaveBeenCalled();

		vi.advanceTimersByTime(1000);

		expect(revokeObjectURL).toHaveBeenCalledWith("blob:reporter-export");
	});
});

function restoreProperty(
	target: object,
	key: string,
	descriptor: PropertyDescriptor | undefined,
) {
	if (descriptor) {
		Object.defineProperty(target, key, descriptor);
		return;
	}
	delete (target as Record<string, unknown>)[key];
}

const meetingWithSummaryMetadata = {
	_id: "meeting_1",
	_creationTime: Date.UTC(2026, 5, 15),
	createdAt: Date.UTC(2026, 5, 14),
	updatedAt: Date.UTC(2026, 5, 16, 12),
	municipalityId: "municipality_1",
	title: "Town Council Regular Meeting",
	meetingType: "city_council",
	meetingDate: Date.UTC(2026, 5, 15),
	status: "summarized",
	sourceUrl: "https://example.test/agenda.pdf",
	sourceType: "scraped",
	contentHash: "meeting-content-hash",
	summary: {
		executiveSummary: "Council reviewed budget and grant items.",
		keyDecisions: [],
		discussionTopics: [],
		upcomingItems: [],
		topics: ["budget"],
		modelUsed: "gpt-4.1-mini",
		promptVersion: "civic-summary-v2",
		processingTimeMs: 4200,
		createdAt: Date.UTC(2026, 5, 15, 12),
		sourceUrl: "https://example.test/agenda.pdf",
		sourceType: "scraped",
		sourceContentHash: "summary-content-hash",
		status: "summarized",
	},
	municipality: {
		_id: "municipality_1",
		name: "Coventry",
		state: "CT",
		lastScrapedAt: Date.UTC(2026, 5, 16, 12),
	},
} as const;

const reporterExportMeeting = {
	...meetingWithSummaryMetadata,
	privateUserId: "private-user-id",
	summary: {
		...meetingWithSummaryMetadata.summary,
		keyDecisions: [
			{
				title: "Approve capital budget",
				description: "Approved the five-year capital plan.",
				voteResult: {
					yes: 5,
					no: 2,
					abstain: 1,
					passed: true,
				},
				topics: ["budget", "infrastructure"],
			},
		],
		discussionTopics: [
			{
				topic: "Housing",
				summary: "Members discussed affordable housing incentives.",
				category: "housing",
			},
		],
		upcomingItems: [{ title: "Budget hearing", expectedDate: "2026-07-01" }],
		privateUserId: "private-user-id",
		subscriptionToken: "subscription-secret",
	},
} as unknown as Parameters<typeof ReporterExportDialog>[0]["meeting"];
